name = "astro-cf-pages"
compatibility_date = "2026-08-09"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[env.production]
name = "astro-cf-pages"
# Uncomment and set your domain to provision it automatically on deploy:
# routes = [{ pattern = "yourdomain.com", custom_domain = true }]
